### ISSUE TITLE
incorrect exe path in entrypoint.sh

### ISSUE THREAD

**Issue by jackgronke** [iAnomaly/docker-ubuntu-steamcmd#1]
The path needs to be updated to DedicatedServer64/

**Comment by iAnomaly** [comment]
Thanks for opening this issue @TheJackG, but AFAIK no one has gotten the 64-bit version of the dedicated server (more specifically .NET) working on WINE.

I think Space Engineers dropped support for the 32-bit version and I'm guessing that's why you are reporting that DedicatedServer/ does not exist anymore?

**Comment by jackgronke** [comment]
@iAnomaly You are right, I opened this issue before I had dug much deeper, my apologies!  

Looks like just about every project that had to do with SE server on Linux are dead or paused due to the 64 bit .NET requirements. 

It's a shame Keen hasn't created (or released) a Linux dedicated server - was horrible to need wine in the first place!

Thanks for the really fast reply though!!

**Comment by iAnomaly** [comment]
@TheJackG You got it. Yes, unfortunately they developed against .NET before .NET Core was stable/viable and many of their 3rd party dependencies like Havok physics would prevent them from migrating now. Official Linux support will probably never happen. :(
